apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: wanderlust
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: srdevop/wanderlust-backend-beta:v1.2
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI
              value: mongodb://mongo-service:27017/wanderlust
            - name: REDIS_URL
              value: redis://redis-service:6379
            - name: PORT
              value: "8080"
            - name: NODE_ENV
              value: "production"
            - name: FRONTEND_URL
              value: http://frontend-service
            - name: ACCESS_COOKIE_MAXAGE
              value: "120000"
            - name: ACCESS_TOKEN_EXPIRES_IN
              value: "120s"
            - name: REFRESH_COOKIE_MAXAGE
              value: "120000"
            - name: REFRESH_TOKEN_EXPIRES_IN
              value: "120s"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: wanderlust
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
